#!/bin/bash

VERSION=$(sed -n 's/.*"\(.*\)".*/\1/p' version.sbt)

if [[ $VERSION == *"-SNAPSHOT" ]]; then
  echo "Commit rejected: cannot push a SNAPSHOT version to remote (found: $VERSION)."
  exit 1
fi

exit 0
